const TYPE_STATUS_PENDING = 1;
const TYPE_STATUS_PROCESSING = 2;
const TYPE_STATUS_DISABLED = 3;
const TYPE_STATUS_ACTIVE = 4;
const TYPE_STATUS_REJECTED = 5;

type TYPE_STATUS =
  typeof TYPE_STATUS_PENDING
  | typeof TYPE_STATUS_PROCESSING
  | typeof TYPE_STATUS_DISABLED
  | typeof TYPE_STATUS_ACTIVE
  | typeof TYPE_STATUS_REJECTED;

export {
  TYPE_STATUS,
  TYPE_STATUS_PENDING,
  TYPE_STATUS_PROCESSING,
  TYPE_STATUS_DISABLED,
  TYPE_STATUS_ACTIVE,
  TYPE_STATUS_REJECTED,
}